### ISSUE TITLE
小白求具体方法

### ISSUE THREAD

**Issue by zionxiao** [Dough-su/ctbulibrary#1]
大佬，请问是网页登录预约界面，直接运行main.py吗？小白一个，有具体的方法吗？盼复，谢谢。

**Comment by Dough-su** [comment]
直接去[release](https://github.com/Dough-su/ctbulibrary/releases)下载对应你系统的压缩包，然后解压后直接运行，把网页的cookie提前复制到软件内，按照软件页面步骤运行就可以
